config/routes.rb
Rails.application.routes.draw do
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :sold_items

  resources :schools

  resources :leagues

  resources :items

  resources :earned_points

  resources :class_jars

  resources :classrooms

  resources :category_codes

  resources :student_class_matches

  resources :student_users

  resources :teacher_users

  root 'pages#home'
  get 'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'privacypolicy' => 'pages#privacypolicy'
  get 'termsofuse' => 'pages#termsofuse'
  get 'pricing'=> 'pages#pricing'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  

end

app/models/category_code.rb
class CategoryCode < ActiveRecord::Base
end

app/models/class_jar.rb
class ClassJar < ActiveRecord::Base
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Classroom Hero Contact",
      :to => "nussbaum.joshua@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/earned_point.rb
class EarnedPoint < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/league.rb
class League < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/sold_item.rb
class SoldItem < ActiveRecord::Base
end

app/models/student_user.rb
class StudentUser < ActiveRecord::Base
	has_one :user, :as => :user_category
	validates :totalcoins, numericality: { greater_than_or_equal_to: 0 }
	validates :currentcoins, numericality: { greater_than_or_equal_to: 0 }
	validates :lvl, numericality: { greater_than_or_equal_to: 1 }
	validates :progress, numericality: { greater_than_or_equal_to: 0 }
end

app/models/teacher_user.rb
class TeacherUser < ActiveRecord::Base
	has_one :user, :as => :user_category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :fname, presence: true
	validates :lname, presence: true
	validates :email, presence: true
	validates_format_of :email, with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\z/
	validates :email, uniqueness: true
	validates :password, :length => { :minimum => 5 }
	validates_confirmation_of :password
	belongs_to :user_category, polymorphic: true
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/class_jars_helper.rb
module ClassJarsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		if @current_user.nil?
			@current_user = User.find_by(:id => session[:user_id])
		else
			@current_user
		end
	end	

	def user_data
		if @user_data.nil?
			if current_user.user_category_type == 'teacher'
				@user_data = TeacherUser.find_by(:id => current_user.user_category_id)
			else
				@user_data = StudentUser.find_by(:id => current_user.user_category_id)
			end
		else
			@user_data
		end
	end

	def is_logged_in
		if session[:user_id].nil?
			return false
		else
			return true
		end
	end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="text-center footer">
	<div id="fb-root"></div>

	<hr style="height:1px;border:none;color:#000;background-color:#000;" />
	<div class="col-md-4">
	  <nav>
	    <ul>
	      <p> Company </p>
	      <li><%= link_to "About",   about_path %></li>
	      <li><%= link_to "Help", help_path %></li>
	      <li><%= link_to "Contact", contacts_path %></li>
	      <li><%= link_to "Privacy Policy", privacypolicy_path %></li>

	    </ul>
	  </nav>
  </div>

  <div class="col-md-4">
  	<ul>
      <li>
        <div style="font-size: 15px; color: black;">
          Spread the word. Like or share us. 
        </div>
      </li><br>
      <li>
        <%= render_shareable :turbolinks => true, :buttons=> ['facebook', 'twitter', 'google_plus', 'linkedin'] %>
      </li><br><br>
      	Copyright &copy; Classroom Hero 2014

  	</ul>

  </div>

  <div class="col-md-4">
	  <nav>
	    <ul>
	      <p> Social </p>
	      <li><a href="https://www.facebook.com/ClassroomHeroHQ?ref=br_tf">Facebook</a></li>
	      <li><a href="https://twitter.com/ClassroomHeroHQ">Twitter</a></li>
	      <li><a href="http://beta.snowshoestamp.com/">SnowShoe Stamps</a></li>

	    </ul>
	  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Classroom Hero", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right header" style="padding-right: 80px;">
        <% if not is_logged_in %>
          <%= link_to "Pricing", pricing_url, {:style=>'outline:none; text-decoration: none !important; color: white; position: relative; top: +9px; left: -13px;'} %>
          <button type="button" class="btn btn-link" data-toggle="modal" data-target="#signUpModal" style="outline:none; text-decoration: none !important; color: white;">
            Sign Up
          </button>
          <button type="button" class="btn btn-link" data-toggle="modal" data-target="#signInModal" style="outline:none; text-decoration: none !important; color: white;">
            Sign In
          </button>
        <% else %>
          <form method="POST" action="/logout" style="display: inline;">
            <input type="hidden" name="_method" value="DELETE" />
            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
            <button type="submit" class="btn btn-link"  style="display: inline; outline: none; text-decoration: none !important; color: white;" >
              Log Out
            </button>
          </form>
          
          <button type="button" class="btn btn-link"  style="outline:none; text-decoration: none !important; color: white;">
            My Account
          </button>
        <% end %>
        <div class="btn-group">
            <button type="button" data-toggle="dropdown" class="btn btn-info dropdown-toggle">Support <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><%= link_to "Help Center", help_url %></li>
                <li class="divider"></li>
                <li><%= link_to "Contact", contacts_path %></li>

            </ul>
        </div>
        

      </ul>
    </nav>
    
    <%= render "layouts/sign_up_modal" %>    
    <%= render "layouts/sign_in_modal" %>

  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sign_in_modal.html.erb
<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <form accept-charset="utf8" action="/login" method="post">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="center modal-title" id="myModalLabel">Sign in</h4>
        </div>
        <div class="modal-body">
          <input type="text" name="session[email]" id="session_email"
			  	class="center input form-control fields" placeholder="Email"
			  	style="max-width: 400px;"><br>
			  	<input type="password" name="session[password]" id="session_password"
			  	class="center input form-control fields" placeholder="Password"
			  	style="max-width: 400px;"><br>
        </div>
        <div class="modal-footer">
          <button type="button" class=" btn btn-default closeButton" data-dismiss="modal">Close</button>
          <input type="submit" name="commit" class=" btn btn-primary" value="Go" >
        </div>
      </div>
    </div>
  </form> 
</div>

app/views/layouts/_sign_up_modal.html.erb
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form accept-charset="UTF-8" method="POST" action="/users" id="signup-form">
        <input name="utf8" type="hidden" value="&#x2713;" />
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>
          <h4 class="center modal-title" id="myModalLabel">Sign up</h4>
        </div>
        <div class="modal-body">
          <input type="text" name="user[fname]" id="first_name"
			  	class="center input form-control fields" placeholder="First Name"
			  	style="max-width: 400px;"><br>
			  	<input type="text" name="user[lname]" id="last_name"
			  	class="center input form-control fields" placeholder="Last Name"
			  	style="max-width: 400px;"><br>
          <input type="text" name="user[email]" id="user_email"
          class="center input form-control fields" placeholder="Email"
          style="max-width: 400px;"><br>
          <input type="password" name="user[password]" id="password"
          class="center input form-control fields" placeholder="Password"
          style="max-width: 400px;"><br>
          <input type="password" name="user[password_confirmation]" id="password_confirmation"
          class="center input form-control fields" placeholder="Confirm Password"
          style="max-width: 400px;"><br>
          <label for="user_type_radios" style="text-align: center; display: block;">I am a:</label>
          <div id="user_type_radios" class="center">
            <label class="radio-inline btn btn-primary" for="student_type" id="student_label">
            <input type="radio" name="user[usertype]" id="student_type"
            class="center input radio-inline type-switch-r" value="student">Student<br>
          </label>
            <label class="radio-inline btn btn-default" for="teacher_type" id="teacher_label">
            <input type="radio" name="user[usertype]" id="teacher_type"
            class="center input radio-inline type-switch-r" value="teacher">Teacher<br>
          </label>
          </div>
        </div>
    </div>
      <div class="modal-footer">
        <button type="button" class=" btn btn-default closeButton" data-dismiss="modal">Close</button>
        <input type="submit" id="btn-login" name="btn-login" class="btn btn-primary" value="Sign Up">
      </div>
      </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'logo.png' %>
    <%= render 'layouts/shim' %>
    
  </head>
  <body>
    
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %> | Classroom Hero</title>
    </head>
    <body>
	    <div class="container">
	    	<div class="dashboard col-md-9 text-center">
	    		<div style="font-size: 32px; font-weight: bold; ">
	    			FAQ
	    			<hr>
	    		</div>
	    		<div class="col-md-6 col-md-offset-3 text-center">

	    			<div class="question"> 
	    				What are SnowShoe Stamps?
	    			</div>
	    			<div class="answer">
	    				Small pieces of plastic with digital identities. Students and teachers stamp the Classroom Hero application to get points, buy items, or add to a class jar. 
	    			</div>

	    			<div class="question"> 
	    				How do I get started?
	    			</div>
	    			<div class="answer">
	    				Create and set up your account, download the application, distribute the stamps, and let the fun begin!  If you do not see your school listed when creating an account, <%= link_to "contact us", contacts_path %> about becoming part of the team. Once logged in, add students, positive reinforcers, items, and a class jar reward to your account. 
	    			</div>

	    			<div class="question"> 
	    				How do I order stamps?
	    			</div>
	    			<div class="answer">
	    				Order stamps by <%= link_to "contacting us", contacts_path %> with your school and classroom information, or order two free stamps from <a href="http://beta.snowshoestamp.com/#order">SnowShoe</a> to test the application.
	    			</div>

	    			<div class="question"> 
	    				How do I register students?
	    			</div>
	    			<div class="answer">
	    				Add students online then log in to the application and you will automatically see the register students screen if you have any to register. Swipe to the correct student, and use an unassigned SnowShoe stamp to register the student.  
	    			</div>

	    			<div class="question"> 
	    				How do I award points?
	    			</div>
	    			<div class="answer">
	    				Once students demonstrate a positive action that is already defined in the application such as, "Volunteer to read", have the student stamp the Reward Screen to claim coins for his positive behavior! 
	    			</div>

	    			<div class="question"> 
	    				What should I do if the stamp is not responding?
	    			</div>
	    			<div class="answer">
	    				Stamping works best with multitasking gestures disabled. Disable multitasking gestures at Settings -> Multitasking Gestures.

	    				Make sure your device has a strong internet connection, as the application does not work offline.  

	    			</div>

	    			<div class="question"> 
	    				What should I do if a students stamp is not working?
	    			</div>
	    			<div class="answer">
	    				If a student is having trouble stamping the screen, try unregistering and re-registering that student. Unregister a student on his student page from the student list. The student list is accessible from the Students on the Home Screen, and the student page is accessed by clicking the student name in the list.
	    			</div>

	    			<div class="question"> 
	    				If I need new stamps, what should I do?
	    			</div>
	    			<div class="answer">
	    				<%= link_to "Contact us", contacts_path %> about ordering more stamps. 
	    			</div>

	    		</div>
			</div>

	        <div class="twitterTimeline col-md-3">
	        	<a class="twitter-timeline"  href="https://twitter.com/ClassroomHeroHQ" data-widget-id="537197085322264578">Tweets by @ClassroomHeroHQ</a>
            	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		    </div>
		</div>
	    </div>
    </body>
</html>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
    <%= javascript_include_tag "application" %>
    <head>
        <title><%= yield(:title) %> | Classroom Hero</title>

    </head>
    <body>


    <div class="center how-it-works-panel"style="display: none; margin: 0 auto; ">
      <button type="button" id="closeDropDown" class="btn btn-default" aria-label="Left Align" style="float: right; margin-right: 1%; margin-top: 1%;">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
      </button><br>
      <h1>Get started</h1>
      <hr style="height:1px;border:none;color:#000;background-color:#000;" />
      <h2 style="color:blue;">Register students with SnowShoe Stamps</h2>
      <h3>Buy stamps, order a free test-kit from <a href="http://beta.snowshoestamp.com/#order">SnowShoe</a>, or <%= link_to "Contact us", contacts_path %> about a free one month trial with enough SnowShoe stamps for your whole class. </h3><br>

      <h2 style="color:blue;">Get ready for class</h2>
      <h3>Create positive actions you want to see repeated, like "Volunteer to read" and award students points for completing these actions. Set up items such as, "Homework pass" to sell to students for their points. </h3><br>

      <h2 style="color:blue;">Let the stamping begin!</h2><br>
      <h3>Simply have students stamp the treasure chest and claim coins</h3><br>
      <hr style="height:1px;border:none;color:#000;background-color:#000;" />
      <button type="button" class="btn btn-md btn-primary" data-toggle="modal" data-target="#signUpModal" style="outline:none">
        Sign up now!
      </button>
      <%= link_to "Learn more", help_url, class: "btn btn-md btn-primary" %>

      <h1></h1>
    </div>

    <header class="splash">
      <div class="center jumbotron">
          <h1>Classroom Hero is an interactive token economy</h1><br>
          <a class="btn btn-md btn-info" id="how-it-works-btn">Get started</a><br>
            
            
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
           
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <div class="carousel-caption">
                  <br><h2>
                    This is not your ordinary reward system. Combined with the magic of
                    <a href="http://beta.snowshoestamp.com/" style="color: lightblue">SnowShoe Stamps</a>, Classroom Hero instantly creates powerful teacher-student interactions
                  </h2><br>
                 
                  <button type="button" class="btn btn-md btn-primary" data-toggle="modal" data-target="#signUpModal" style="outline:none">
                    Sign up
                  </button>
                  <button type="button" class="btn btn-md btn-primary" data-toggle="modal" data-target="#signInModal" style="outline:none">
                    Sign in
                  </button>
                
                </div>
              </div>
              <div class="item">
                <div class="carousel-caption">
                    <br><h2>Motivate a generation of learners with technology that will increase participation and engagement</h2><br>
                    <%= link_to "Learn more", help_url, class: "btn btn-sm btn-primary" %>
                </div>
              </div>
              <div class="item">
                <div class="carousel-caption">
                    <br><h2>Hear from teachers and students using Classroom Hero </h2><br>
                    <a class="btn btn-sm btn-primary" href="#teacherVideos"> Videos </a>
                    <br>
                </div>
              </div>
            </div>
           
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
            
          </div> 
          <!-- Carousel -->
      </div>

    </header>
    <div  id="scrollsection">
      <div class="col-md-12" style="text-align: center; position: relative; top: +50px; margin-bottom: 50px;">
        <div class="small-4 large-4 columns" style="font-size: 25px; color: black; margin-top: 35px; margin-bottom: 360px;">
          <%= scroll_reveal(content: 'Scroll down to see how Classroom Hero works', animation: 'enter top over 1.0s') %>
             <%= scroll_reveal(animation: "enter top over 1.0s" ) do %>
                <div style="color: blue; size: 200%; margin-top: 20px;"><i class="glyphicon glyphicon-arrow-down" ></i></div>
              <% end %>
          

        </div>
        
  

        <div class="small-4 large-4 columns" style="font-size: 25px; color: black; margin-top: 200px; margin-bottom: 25px;"><%= scroll_reveal(content: 'Award points for positive actions', animation: 'enter top over 1.0s') %></div><br><br>


        <div class="row">
          <div class="small-2 large-4 columns">
            <%= scroll_reveal(animation: "enter bottom, over .5s" ) do %>
              <%= image_tag 'rewardscreen.png' %>
            <% end %>
            <div class="small-2 large-4 columns" style="position: relative; top: -290px; left: -17px">
              <%= scroll_reveal(animation: "enter bottom, and move 350px after .7s" ) do %>
                <%= image_tag 'stamp.png' %>
              <% end %>
            </div>
          </div>

          <div class="small-4 large-4 columns" style="font-size: 25px; color: black; margin-top: 50px; margin-bottom: 25px;"><%= scroll_reveal(content: 'Sell items and privileges for hard-earned points', animation: 'enter top over 1.0s') %></div><br><br>
         
          <div class="small-2 large-4 columns">
          <%= scroll_reveal(animation: "enter top, over .5s" ) do %>
              <%= image_tag 'sellscreen.png' %>
            <% end %>
          </div>
          <div class="small-2 large-4 columns" style="position: relative; top: -292px; left: -5px">
            <%= scroll_reveal(animation: "enter bottom, and move 350px after .7s" ) do %>
              <%= image_tag 'stamp.png' %>
            <% end %>
          </div>

          <div class="small-4 large-4 columns" style="font-size: 25px; color: black; margin-top: 50px; margin-bottom: 25px;"><%= scroll_reveal(content: 'Add points to a classroom jar to keep every student engaged!', animation: 'enter top over 1.0s') %></div><br><br>

          <div class="small-2 large-4 columns">
          <%= scroll_reveal(animation: "enter top, over .5s" ) do %>
              <%= image_tag 'jarscreen.png' %>
            <% end %>
          </div>
          <div class="small-2 large-4 columns" style="position: relative; top: -285px; left: -5px">
            <%= scroll_reveal(animation: "enter bottom, and move 350px after .7s" ) do %>
              <%= image_tag 'stamp.png' %>
            <% end %>

          </div>
          <hr style="height:1px;border:none;color:#000;background-color:#000;" />


        </div>
      </div>
      
    </div>

    <div class="row">
      <div class="row text-center promoVideos">
        <div class="col-md-6">
          <div id="teacherVideos"></div>
          <iframe src="//www.youtube.com/embed/bJ4EFh7oWJc" width="380" height="300" scrolling="no" webkitallowfullscreen mozallowfullscreen>
          </iframe>
        </div>
        <div class="col-md-6">
          <iframe src="//www.youtube.com/embed/RX2e2b4o6fk" width="380" height="300" scrolling="no" webkitallowfullscreen mozallowfullscreen>
          </iframe>
        </div>
      </div>
      <div class="row text-center demoVideos">

        <h1>Classroom Hero videos</h1>

        <div class="col-md-4">
          <iframe src="//www.youtube.com/embed/yOO31PwUpOs" width="380" height="300" scrolling="no" webkitallowfullscreen mozallowfullscreen>
          </iframe>
        </div>
        
        <div class="col-md-4">
          <iframe src="//www.youtube.com/embed/gisLhagdeDg" width="380" height="300" scrolling="no" webkitallowfullscreen mozallowfullscreen>
          </iframe>
        </div>
        <div class="col-md-4">
          <iframe src="//www.youtube.com/embed/g0gtK-tmDE0" width="380" height="300" scrolling="no" webkitallowfullscreen mozallowfullscreen>
          </iframe>
        </div>
      </div>
    </div>
    <hr style="height:1px;border:none;color:#000;background-color:#000;" />

    <div class="row">

      <div class="col-sm-4 col-sm-offset-1">
        <br><br>
        <%= image_tag('info1.png') %>
      </div>
      <div class="infoDescription col-md-5 col-md-offset-2">
        <div style="font-size: 25px; color: black;">
          Create a classroom community
        </div>
      </div>
    </div>

    <div class="row">
      <div class="infoDescription col-sm-4 col-sm-offset-1">
        <br><br>
          <div style="font-size: 25px; color: black;">
          Augment reality with a touch of plastic
        </div> 
      </div>
      <div class="col-md-5 col-md-offset-2">
        <%= image_tag('info2.png') %>
      </div>

    </div>

    <div class="row">

      <div class="col-sm-4 col-sm-offset-1">
        <br><br>
        <%= image_tag('info3.png') %>
      </div>
      <div class="infoDescription col-md-5 col-md-offset-2">
        <div style="font-size: 25px; color: black;">
          Epic win
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/pricing.html.erb
<% provide(:title, "Pricing") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %>| Classroom Hero</title>
    </head>
    <body>
        <br><h3 class="text-center">Pricing</h3>
        <div class="row" style="max-width: 20%; margin: 0 auto;">
        	<hr>
        </div>

        <div class="row" style="max-width: 50%; margin: 0 auto;">
        	<div class="col-md-12 text-center">
        		<div style="text-transform: uppercase; font-size: 18px; font-weight: bold; margin-bottom: 30px; margin-top: 15px;"> We have a plan to fit your classroom and budget</div>
        		<p> Order a <a href="http://beta.snowshoestamp.com/#order">free test-kit</a> from SnowShoe to test the stamps with the application. After deciding you want the stamps, <%= link_to "contact us", contacts_path %> to discuss our flexible pricing options.
        	</div>
        </div>

        <div class="row" style="background-color: lightgray; margin-top: 50px; min-height: 300px;">
        	<div class="col-md-4 col-md-offset-2 text-center">
        		<div style="text-transform: uppercase; font-size: 18px; font-weight: bold; margin-bottom: 30px; margin-top: 15px; color: blue"> Option 1
        		</div>
        		<p> Pay what you can. </p>

        	</div>

        	<div class="col-md-4 text-center">
        		<div style="text-transform: uppercase; font-size: 18px; font-weight: bold; margin-bottom: 30px; margin-top: 15px; color: blue"> Option 2
        		</div>
        		<p> $5/month per classroom. </p>
        		
        	</div>
        </div>

        <div class="row">
        	<div class="col-md-12 text-center" style="margin-top: 50px;">
        		<p> Interested in a free trial, or purchasing stamps? Contact us today!</p>
                <%= link_to "Contact us", contacts_path, class: "btn btn-warning btn-primary" %>


    </body>
</html>

app/views/pages/privacypolicy.html.erb
<% provide(:title, "Privacy Policy") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %>| Classroom Hero</title>
    </head>
    <body>
        <h1>Privacy Policy</h1><br>
        <p>
            Classroom Hero Privacy Policy Page
        </p>
    </body>
</html>

app/views/pages/termsofuse.html.erb
<% provide(:title, "Terms of Use") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %>| Classroom Hero</title>
    </head>
    <body>
        <h1>Terms of Use</h1><br>
        <p>
            Classroom Hero Terms of Use
        </p>
    </body>
</html>